---
# Reference: https://github.com/CaddyBuilds/caddy-cloudflare

services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:2
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    #ports:  # use for rootless
    #  - "80:80"
    #  - "443:443"
    #  - "443:443/udp"
    network_mode: host  # use for rootful
    healthcheck:
      test: ["CMD-SHELL","curl -k -f http://localhost:80 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - /home/iurii/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - /home/iurii/docker/caddy/caddy_data:/data:Z
      - /home/iurii/docker/caddy/caddy_config:/config:Z
