---
# Reference: https://github.com/CaddyBuilds/caddy-cloudflare

services:
  caddy:
    image: ghcr.io/caddybuilds/caddy-cloudflare:2
    container_name: caddy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    extra_hosts:
      - "host.docker.internal:10.0.2.2"
    env_file:
      - .env
    logging:
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - /home/iurii/docker/caddy/Caddyfile:/etc/caddy/Caddyfile:Z
      - /home/iurii/docker/caddy/caddy_data:/data:Z
      - /home/iurii/docker/caddy/caddy_config:/config:Z
    networks:
      - shared

networks:
  shared:
    external: true
