# Reference: https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml

services:
  # https://servicestack.net/posts/hosting-llama-server
  # gpt-oss:
  #   image: ghcr.io/ggml-org/llama.cpp:server-cuda
  #   container_name: gpt-oss
  #   environment:
  #     # - LLAMA_ARG_N_GPU_LAYERS=999
  #     - LLAMA_ARG_MODEL=/models/gpt-oss-20b-Q4_K_M.gguf
  #   ports:
  #     - "10000:8080"
  #   volumes:
  #     # https://huggingface.co/unsloth/gpt-oss-20b-GGUF/resolve/main/gpt-oss-20b-Q4_K_M.gguf
  #     - /home/iurii/docker/ollama-openwebui/models:/models
  #   deploy:
  #     resources:
  #       reservations:
  #         devices:
  #           - driver: nvidia
  #             count: all
  #             capabilities: [gpu]

  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
    volumes:
      - /home/iurii/docker/ollama-openwebui/ollama:/root/.ollama
      - /home/iurii/docker/ollama-openwebui/models:/models
    ports:
      - "127.0.0.1:11434:11434"
    restart: unless-stopped
    pull_policy: always
    environment:
      - OLLAMA_CONTEXT_LENGTH=8192
      - JWT_EXPIRES_IN=3600
      - USER_AGENT=ollama
      - CORS_ALLOW_ORIGIN=http://localhost:8082,https://ollama.iurii.io
      - OLLAMA_KEEP_ALIVE=-1
      - OLLAMA_FLASH_ATTENTION=1
      - OLLAMA_KV_CACHE_TYPE=q8_0

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "127.0.0.1:8082:8080"
    volumes:
      - /home/iurii/docker/ollama-openwebui/open-webui:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    environment:
      - OLLAMA_BASE_URL=https://ollama.iurii.io
      - CORS_ALLOW_ORIGIN=https://ollama.iurii.io
      - WEBUI_SECRET_KEY=  # will just be generated when run
    extra_hosts:
      - host.docker.internal:host-gateway