# Reference: https://github.com/open-webui/open-webui/blob/main/docker-compose.yaml

services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
              count: ${OLLAMA_GPU_COUNT-1}
              capabilities:
                - gpu
    volumes:
      - /home/iurii/docker/ollama-openwebui/ollama:/root/.ollama
    ports:
      - "127.0.0.1:11434:11434"
    restart: unless-stopped
    pull_policy: always
    environment:
      - OLLAMA_CONTEXT_LENGTH=4096
      - JWT_EXPIRES_IN=3600
      - CORS_ALLOW_ORIGIN=http://localhost:8082,https://ollama.iurii.io
      - USER_AGENT=ollama

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "127.0.0.1:8082:8080"
    volumes:
      - /home/iurii/docker/ollama-openwebui/open-webui:/app/backend/data
    depends_on:
      - ollama
    restart: unless-stopped
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - CORS_ALLOW_ORIGIN=http://localhost:8082,https://ollama.iurii.io
      - 'WEBUI_SECRET_KEY='  # will just be generated when run
    extra_hosts:
      - host.docker.internal:host-gateway