# References:
# https://github.com/linuxserver/docker-sonarr
# https://github.com/linuxserver/docker-radarr
# https://github.com/linuxserver/docker-lidarr
# https://github.com/linuxserver/docker-prowlarr
# https://github.com/qdm12/gluetun-wiki/
# https://hub.docker.com/r/linuxserver/qbittorrent/

---
services:
  sonarr:  # tv series downloader
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    env_file:
      - .env
    volumes:
      - /home/iurii/docker/torrenting/sonarr-config:/config
      - /mnt/data/jellyfin/tv:/tv
      - /mnt/data/jellyfin/downloads:/downloads
    ports:
      - 127.0.0.1:8989:8989
    restart: unless-stopped
    networks:
      - shared

  radarr:  # movies downloader
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    env_file:
      - .env
    volumes:
      - /home/iurii/docker/torrenting/radarr-config:/config
      - /mnt/data/jellyfin/movies:/movies
      - /mnt/data/jellyfin/downloads:/downloads
    ports:
      - 127.0.0.1:7878:7878
    restart: unless-stopped
    networks:
      - shared

  lidarr:  # music downloader
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    env_file:
      - .env
    volumes:
      - /home/iurii/docker/torrenting/lidarr-config:/config
      - /mnt/data/jellyfin/music:/music
      - /mnt/data/jellyfin/downloads:/downloads
    ports:
      - 127.0.0.1:8686:8686
    restart: unless-stopped
    networks:
      - shared

  prowlarr:  # indexer manager
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    env_file:
      - .env
    volumes:
      - /home/iurii/docker/torrenting/prowlarr-config:/config
    ports:
      - 127.0.0.1:9696:9696
    restart: unless-stopped
    networks:
      - shared

  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # See https://github.com/qdm12/gluetun-wiki/blob/main/setup/connect-a-container-to-gluetun.md#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 127.0.0.1:8085:8085
      - 127.0.0.1:6881:6881
      - 127.0.0.1:6881:6881/udp
      # - 127.0.0.1:8888:8888/tcp # HTTP proxy
      # - 127.0.0.1:8388:8388/tcp # Shadowsocks
      # - 127.0.0.1:8388:8388/udp # Shadowsocks
    volumes:
      - /home/iurii/docker/torrenting/gluetun-data:/gluetun
    env_file:
      - .env
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    env_file:
      - .env
    network_mode: "service:gluetun"
    volumes:
      - /home/iurii/docker/torrenting/qbittorrent-config:/config
      - /mnt/data/jellyfin/downloads:/downloads
      - /mnt/data/wiki:/wiki
    restart: unless-stopped

networks:
  shared:
    driver: bridge
