---
# https://github.com/gethomepage/homepage

services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    env_file:
      - .env
    ports:
      - "127.0.0.1:3000:3000"
    volumes:
      - /home/iurii/docker/homepage/config:/app/config  # make sure this directory exists.
      - /run/user/1000/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    logging:
      options:
        max-size: 10m
        max-file: "3"