---
# Reference: https://github.com/kiwix/kiwix-tools/blob/main/docker/server/docker-compose.yml.example

services:
  kiwix-serve:
    image: ghcr.io/kiwix/kiwix-serve
    container_name: kiwix
    environment:
      - TZ=America/Chicago
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    volumes:
      - /mnt/data/wiki:/data:ro
    ports:
      - 127.0.0.1:8080:8080
    command: '*.zim'
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL","wget -q --spider http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:
      options:
        max-size: 10m
        max-file: "3"